[REFACTOR] Data Model & Layered Architecture
pkitazos/spa pull request #255
Opened 2024-12-26 11:05 UTC by pkitazos

# New Data Model
- needed to model the new features the platform needs to support
- fixes some inconsistencies from the previous version

# Migration to Layered Architecture
- decouple business logic from database and ORM
- make testing business logic and data-access functions separately easier

2024-12-26 11:11 UTC, pkitazos commented on src/server/routers/institution/instance/index.ts
@JakeTrevor this is the point of entry for the review I would say. Start here and control-click through to the functions you wanna see the internals of

2025-01-04 01:56 UTC, JakeTrevor requested changes
OK, its a monster PR so you get a monster review.

There are a couple outright problems - in the prisma schema mostly - but broadly I think its a move in the right direction.

A couple other thigns that I didn't get around to putting in the code comments:

### Transactions
The transactions are awful, but I don't have any better ideas. 


### tRPC middleware
the biggest single thing (or so it seems to me) standing between you and code paradise is the middleware. I think it's just straight up factored incorrectly, and we should review it.
The biggest offender is the instanceAdminProcedure. Because of how that inherits, it causes some very ugly types and require you to add arbitrary `.input`s that just re-specify the instance params. This is incredibly dumb, and I am convinced there must be a way to get rid of it.

There are lots of ways we could approach this, but the middleware seems to be its own nest of horrible code snakes. I don't want to dig into it now when the review is already so long and the subject is out of scope.

For now, we can of course use the suggestion of grabbing the params off the instance - if you do in fact prefer that. And it might all end up being irrelevant, depending on:

### Data objects
instance should definitely be a data object, and we should associate the data-fetching and mutation methods with it.

In truth, I am not really convinced of the value of "use cases" - seems to me that a DAL is sufficient. I'm interested to hear your reasoning on including it.

So far, my view is that well factored data objects will obviate the need for separation. But who knows - I could well be wrong.

---
Great work as ever. If I ever seem too harsh please remeber that I do in fact think this is great work done by a very talented programmer :-)

2025-01-04 01:56 UTC, JakeTrevor commented on src/server/routers/institution/instance/index.ts
You have two procedures, one `supervisors` and one `getSupervisors`. Consider renaming?

2025-01-04 01:56 UTC, JakeTrevor commented on src/server/routers/institution/instance/index.ts
>  });
Consider moving this method to the top, with the other "simple access" methods?

I think you might consider moving quite a few of these around - perhaps even separating them out into a secondary router - or at least another file.

For example, you could do `instance.data` -> details like getFlags, get supervisors, etc. Generally the methods that do not require admin privilege. 

You could go for something else though, and after moving some stuff around might also be fine as is. Happy to brainstorm :)

2025-01-04 01:56 UTC, JakeTrevor commented on src/server/routers/institution/instance/index.ts
The extra input is quite annoying and ugly. With a bit of cleverness, you can get this down to 2 lines:

```suggestion
  projectAllocations: instanceAdminProcedure.query(async ({ ctx }) => {
    return await getProjectAllocationsUseCase({ params: ctx.instance.params });
  }),
```
Since we pull the params of the `ctx.instance` they have the right type. In general, you can do this for all your other admin procedures. I've got a version of the file where I implemented a lot of these and it really trims them down. Most of them are a very neat 2 line thing. I won't add suggestions for those for the sake of noise, but I can provide a patch file.

2025-01-04 02:00 UTC, JakeTrevor commented on src/interactors/index.ts
> +  return { byStudent, byProject, bySupervisor };
alternate name might be `toViews()`

2025-03-03 18:27 UTC, closed without merging